version: "3.7"

services:
  engram-api:
    image: xyzdigital/engram-api:latest
    ports:
      - 4000:4000
    secrets:
      - db_url
      - jwt_secret
  engram-static:
    image: xyzdigital/engram-static:latest
    ports:
      - 80:80

secrets:
  db_url:
    external: true
  jwt_secret:
    external: true
